// Package api - setup_wizard.go implements an in-app guided setup flow that
// walks a user through the same Media-groups -> Paths -> Indexer -> Downloader
// -> Lists -> Finalize chain that would otherwise require hand-editing
// config.toml. Every step is optional/skippable.
//
// The flow deliberately asks "which media groups?" first (step 1), so the
// Paths step (step 2) already knows how many paths to ask for per group
// (a Library path and an optional Import path) and which file extensions to
// apply automatically - the user never has to pick a "kind" separately.
// Indexer/Downloader stay single-item wizard forms with a live Test
// Connection button. Lists embeds the real Settings section (every list type,
// unlimited add). Finalize wires paths+lists+a per-group quality/regex
// profile into the actual media groups. State between steps is carried in
// hidden form fields (see wizardState) rather than server-side session
// storage, so each request stays stateless.
package api

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/deluge"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/newznab"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/nzbget"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/qbittorrent"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/rtorrent"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/sabnzbd"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/providers/transmission"
	"github.com/Kellerman81/go_media_downloader/pkg/main/config"
	"github.com/gin-gonic/gin"
	"maragu.dev/gomponents"
	hx "maragu.dev/gomponents-htmx"
	"maragu.dev/gomponents/html"
)

const (
	wizardTestTimeout = 10 * time.Second
	wizardDefaultName = "Wizard-Default"
	wizardLastStep    = 7
)

var wizardStepLabels = []string{
	"Media Groups",
	"Storage Paths",
	"Indexer",
	"Download Client",
	"Lists",
	"Finalize",
	"Finish",
}

// wizardGroupState is what step 1 (selection) and step 2 (paths) accumulate
// per media group before step 6 (finalize) turns it into a real
// MediaTypeConfig.
type wizardGroupState struct {
	Enabled     bool
	Name        string
	LibraryPath string // PathsConfig.Name for the group's Data path
	ImportPath  string // PathsConfig.Name for the group's DataImport path
}

// wizardState carries what earlier steps decided across requests via hidden
// form fields - there is no server-side wizard session.
type wizardState struct {
	Indexer    string
	Downloader string
	Groups     map[string]wizardGroupState // keyed by wizardMediaGroupDef.key
}

// ---- Page entry point ----

func adminPageSetupWizard(ctx *gin.Context) {
	csrfToken := getCSRFToken(ctx)
	pageNode := page("Setup Wizard", false, false, true, renderSetupWizardShell(csrfToken))

	var buf strings.Builder
	pageNode.Render(&buf)

	ctx.Header("Content-Type", "text/html")
	ctx.String(http.StatusOK, buf.String())
}

func renderSetupWizardShell(csrfToken string) gomponents.Node {
	return html.Div(
		html.Class("col-12"),
		html.Div(
			html.Class("d-flex justify-content-between align-items-start"),
			renderEnhancedPageHeader(
				"fa-solid fa-wand-magic-sparkles",
				"Setup Wizard",
				"Walks you through the basic configuration (media groups, storage paths, an indexer, a download client, and lists) that would otherwise need hand-editing config.toml. Every step is optional - skip anything you'd rather configure later under Settings.",
			),
			html.A(
				html.Class("btn btn-sm btn-outline-secondary ms-3 flex-shrink-0"),
				html.Href("/api/admin/wizard/dismiss"),
				gomponents.Text("Skip wizard, go to Dashboard"),
			),
		),
		html.Div(
			html.ID("wizard-step-content"),
			renderWizardFragment(1, csrfToken, wizardState{}),
		),
	)
}

// wizardConfigLooksDefault reports whether every section ClearCfg seeds is
// still exactly its untouched placeholder ("initial"/empty) - i.e. the config
// was generated by ClearCfg and nobody has configured anything since.
func wizardConfigLooksDefault() bool {
	isInitialOnly := func(names []string) bool {
		return len(names) == 1 && names[0] == "initial"
	}

	downloaders := wizardNames(
		config.GetSettingsDownloaderAll(),
		func(d config.DownloaderConfig) string { return d.Name },
	)
	indexers := wizardNames(
		config.GetSettingsIndexerAll(),
		func(i config.IndexersConfig) string { return i.Name },
	)
	paths := wizardNames(config.GetSettingsPathAll(), func(p config.PathsConfig) string { return p.Name })
	lists := wizardNames(config.GetSettingsListAll(), func(l config.ListsConfig) string { return l.Name })

	if !isInitialOnly(downloaders) || !isInitialOnly(indexers) || !isInitialOnly(paths) ||
		!isInitialOnly(lists) {
		return false
	}

	media := config.GetSettingsMediaAll()
	if media == nil {
		return false
	}

	movies := wizardNames(media.Movies, func(m config.MediaTypeConfig) string { return m.Name })
	series := wizardNames(media.Series, func(m config.MediaTypeConfig) string { return m.Name })

	if !isInitialOnly(movies) || !isInitialOnly(series) {
		return false
	}

	return len(media.Books) == 0 && len(media.AudioBooks) == 0 && len(media.Music) == 0
}

// HandleWizardDismiss marks the current session as having seen the wizard so
// the dashboard stops auto-redirecting to it, then sends the user on to the
// dashboard.
func HandleWizardDismiss(c *gin.Context) {
	if sessionCookie, err := c.Cookie("session_id"); err == nil {
		sessionStore.markWizardDismissed(sessionCookie)
	}

	c.Redirect(http.StatusFound, "/api/admin")
}

// ---- Routing handlers ----

// HandleWizardStepGet renders a step fragment with fresh data - used both for
// forward navigation and for reloading a step.
func HandleWizardStepGet(c *gin.Context) {
	n := wizardParseStep(c.Param("n"))
	state := readWizardState(c)
	csrfToken := getCSRFToken(c)

	c.Header("Content-Type", "text/html")
	c.String(http.StatusOK, renderComponentToString(renderWizardFragment(n, csrfToken, state)))
}

// HandleWizardStepSave saves step n's own contribution and returns the
// rendered fragment for step n+1. Steps 5 (Lists) has no case here - it saves
// via the embedded Settings section's own endpoint instead.
func HandleWizardStepSave(c *gin.Context) {
	if err := c.Request.ParseForm(); err != nil {
		c.Header("Content-Type", "text/html")
		c.String(http.StatusOK, renderAlert("Failed to parse form data: "+err.Error(), "danger"))

		return
	}

	n := wizardParseStep(c.Param("n"))
	state := readWizardState(c)
	csrfToken := getCSRFToken(c)

	var alert string

	switch n {
	case 1:
		alert, state.Groups = wizardSaveGroupsStep(c, state)
	case 2:
		alert, state.Groups = wizardSavePathsStep(c, state)
	case 3:
		var name string

		alert, name = wizardSaveIndexerStep(c)
		if name != "" {
			state.Indexer = name
		}
	case 4:
		var name string

		alert, name = wizardSaveDownloaderStep(c)
		if name != "" {
			state.Downloader = name
		}
	case 6:
		alert = wizardSaveFinalizeStep(c, state)
	}

	next := n + 1
	if next > wizardLastStep {
		next = wizardLastStep
	}

	c.Header("Content-Type", "text/html")
	c.String(http.StatusOK, alert+renderComponentToString(renderWizardFragment(next, csrfToken, state)))
}

func wizardParseStep(raw string) int {
	n, err := strconv.Atoi(raw)
	if err != nil || n < 1 || n > wizardLastStep {
		return 1
	}

	return n
}

// wizardFormOrQuery reads a value posted as form data (Save) or as a query
// string parameter (Skip/Continue, which htmx sends as a plain GET with
// included values serialized into the URL).
func wizardFormOrQuery(c *gin.Context, key string) string {
	if v := c.PostForm(key); v != "" {
		return v
	}

	return c.Query(key)
}

func readWizardState(c *gin.Context) wizardState {
	state := wizardState{
		Indexer:    wizardFormOrQuery(c, "wizard_ctx_indexer"),
		Downloader: wizardFormOrQuery(c, "wizard_ctx_downloader"),
		Groups:     make(map[string]wizardGroupState, len(wizardMediaGroupDefs)),
	}

	for _, d := range wizardMediaGroupDefs {
		g := wizardGroupState{
			Enabled:     wizardFormOrQuery(c, "wizard_ctx_group_"+d.key+"_enabled") != "",
			Name:        wizardFormOrQuery(c, "wizard_ctx_group_"+d.key+"_name"),
			LibraryPath: wizardFormOrQuery(c, "wizard_ctx_group_"+d.key+"_library"),
			ImportPath:  wizardFormOrQuery(c, "wizard_ctx_group_"+d.key+"_import"),
		}
		if g.Enabled || g.Name != "" || g.LibraryPath != "" || g.ImportPath != "" {
			state.Groups[d.key] = g
		}
	}

	return state
}

func wizardHiddenState(state wizardState) gomponents.Node {
	nodes := []gomponents.Node{
		html.Input(html.Type("hidden"), html.Name("wizard_ctx_indexer"), html.Value(state.Indexer)),
		html.Input(
			html.Type("hidden"),
			html.Name("wizard_ctx_downloader"),
			html.Value(state.Downloader),
		),
	}

	for _, d := range wizardMediaGroupDefs {
		g := state.Groups[d.key]

		enabled := ""
		if g.Enabled {
			enabled = "1"
		}

		nodes = append(nodes,
			html.Input(
				html.Type("hidden"),
				html.Name("wizard_ctx_group_"+d.key+"_enabled"),
				html.Value(enabled),
			),
			html.Input(
				html.Type("hidden"),
				html.Name("wizard_ctx_group_"+d.key+"_name"),
				html.Value(g.Name),
			),
			html.Input(
				html.Type("hidden"),
				html.Name("wizard_ctx_group_"+d.key+"_library"),
				html.Value(g.LibraryPath),
			),
			html.Input(
				html.Type("hidden"),
				html.Name("wizard_ctx_group_"+d.key+"_import"),
				html.Value(g.ImportPath),
			),
		)
	}

	return gomponents.Group(nodes)
}

// ---- Fragment dispatch ----

func renderWizardFragment(step int, csrfToken string, state wizardState) gomponents.Node {
	var body gomponents.Node

	switch step {
	case 1:
		body = renderWizardStepGroups(csrfToken, state)
	case 2:
		body = renderWizardStepPaths(csrfToken, state)
	case 3:
		body = renderWizardStepIndexer(csrfToken)
	case 4:
		body = renderWizardStepDownloader(csrfToken)
	case 5:
		body = renderWizardStepLists(csrfToken)
	case 6:
		body = renderWizardStepFinalize(csrfToken, state)
	default:
		body = renderWizardStepFinish()
	}

	// wizardCarry holds the hidden state fields outside any particular step's
	// own <form>, so every nav/save button (whose hx-include lists this div)
	// keeps forwarding the accumulated selections regardless of whether the
	// current step has its own form (step 5 doesn't).
	return html.Div(
		wizardProgressBar(step),
		html.Div(html.ID("wizardCarry"), wizardHiddenState(state)),
		body,
	)
}

func wizardProgressBar(active int) gomponents.Node {
	items := make([]gomponents.Node, 0, len(wizardStepLabels))

	for i, label := range wizardStepLabels {
		n := i + 1
		class := "badge rounded-pill bg-secondary me-2 mb-2"

		switch {
		case n == active:
			class = "badge rounded-pill bg-primary me-2 mb-2"
		case n < active:
			class = "badge rounded-pill bg-success me-2 mb-2"
		}

		items = append(
			items,
			html.Span(html.Class(class), gomponents.Text(fmt.Sprintf("%d. %s", n, label))),
		)
	}

	return html.Div(html.Class("mb-3"), gomponents.Group(items))
}

func wizardCSRFHeader(csrfToken string) string {
	return "{\"X-CSRF-Token\": \"" + csrfToken + "\"}"
}

func wizardSaveButton(step int, csrfToken string) gomponents.Node {
	return html.Button(
		html.Class("btn btn-primary me-2"),
		html.Type("button"),
		gomponents.Text("Save & Continue"),
		hx.Target("#wizard-step-content"),
		hx.Swap("innerHTML"),
		hx.Post(fmt.Sprintf("/api/admin/wizard/step/%d", step)),
		hx.Include("#wizardStepForm, #wizardCarry"),
		hx.Headers(wizardCSRFHeader(csrfToken)),
	)
}

// wizardNextButton just moves to the next step without saving anything of its
// own - used for "Skip" on wizard-form steps and "Continue" on the embedded
// Lists step (which saves via its own section's Save button instead).
func wizardNextButton(step int, label string) gomponents.Node {
	return html.Button(
		html.Class("btn btn-outline-secondary"),
		html.Type("button"),
		gomponents.Text(label),
		hx.Target("#wizard-step-content"),
		hx.Swap("innerHTML"),
		hx.Get(fmt.Sprintf("/api/admin/wizard/step/%d", step+1)),
		hx.Include("#wizardCarry"),
	)
}

func wizardTestButton(url, csrfToken string) gomponents.Node {
	return html.Button(
		html.Class("btn btn-outline-info me-2"),
		html.Type("button"),
		gomponents.Text("Test Connection"),
		hx.Target("#wizardTestResult"),
		hx.Swap("innerHTML"),
		hx.Post(url),
		hx.Include("#wizardStepForm, #wizardCarry"),
		hx.Headers(wizardCSRFHeader(csrfToken)),
	)
}

// wizardNames extracts Name-like fields via the given accessor.
func wizardNames[T any](items []T, name func(T) string) []string {
	out := make([]string, 0, len(items))
	for _, it := range items {
		out = append(out, name(it))
	}

	return out
}

func wizardNameExists(names []string, want string) bool {
	for _, n := range names {
		if n == want {
			return true
		}
	}

	return false
}

// wizardNonEmpty filters out blank entries (a selectarray with nothing chosen
// can still post a single empty-string value).
func wizardNonEmpty(values []string) []string {
	out := make([]string, 0, len(values))

	for _, v := range values {
		if v != "" {
			out = append(out, v)
		}
	}

	return out
}

// ---- Media group definitions (shared by steps 1, 2 and 6) ----

// wizardMediaGroupDef describes one of the five fixed media-type groups the
// wizard can create, including which per-type quality/extension defaults to
// use.
type wizardMediaGroupDef struct {
	key           string // stable identifier: "movies","series","music","audiobooks","books"
	enabledField  string
	nameField     string
	label         string
	defaultName   string
	audibleRegion string
	qualityKind   string // "video","music","audiobook","book" - drives extension + quality defaults
	target        func(*config.MediaConfig) *[]config.MediaTypeConfig
}

var wizardMediaGroupDefs = []wizardMediaGroupDef{
	{
		key: "movies", enabledField: "EnableMovies", nameField: "NameMovies",
		label: "Movies", defaultName: "Movies", qualityKind: "video",
		target: func(mc *config.MediaConfig) *[]config.MediaTypeConfig { return &mc.Movies },
	},
	{
		key: "series", enabledField: "EnableSeries", nameField: "NameSeries",
		label: "Series", defaultName: "Series", qualityKind: "video",
		target: func(mc *config.MediaConfig) *[]config.MediaTypeConfig { return &mc.Series },
	},
	{
		key: "music", enabledField: "EnableMusic", nameField: "NameMusic",
		label: "Music", defaultName: "Music", qualityKind: "music",
		target: func(mc *config.MediaConfig) *[]config.MediaTypeConfig { return &mc.Music },
	},
	{
		key: "audiobooks", enabledField: "EnableAudiobooks", nameField: "NameAudiobooks",
		label: "Audiobooks", defaultName: "Audiobooks",
		audibleRegion: "us", qualityKind: "audiobook",
		target: func(mc *config.MediaConfig) *[]config.MediaTypeConfig { return &mc.AudioBooks },
	},
	{
		key: "books", enabledField: "EnableBooks", nameField: "NameBooks",
		label: "Books", defaultName: "Books", qualityKind: "book",
		target: func(mc *config.MediaConfig) *[]config.MediaTypeConfig { return &mc.Books },
	},
}

func wizardEnabledGroups(state wizardState) []wizardMediaGroupDef {
	out := make([]wizardMediaGroupDef, 0, len(wizardMediaGroupDefs))

	for _, d := range wizardMediaGroupDefs {
		if state.Groups[d.key].Enabled {
			out = append(out, d)
		}
	}

	return out
}

// wizardApplyExtensions sets the allowed-extension fields on cfg based on a
// group's media kind, so the Paths step never has to ask the user to pick
// extensions manually.
func wizardApplyExtensions(cfg *config.PathsConfig, kind string) {
	switch kind {
	case "video":
		cfg.AllowedVideoExtensions = []string{".mkv", ".mp4", ".avi", ".m4v"}
		cfg.AllowedOtherExtensions = []string{".srt", ".nfo", ".idx", ".sub"}
	case "music", "audiobook":
		cfg.AllowedAudioExtensions = []string{".mp3", ".flac", ".m4a", ".m4b", ".ogg", ".opus"}
	case "book":
		cfg.AllowedBookExtensions = []string{".epub", ".pdf", ".mobi", ".azw3"}
	}
}

func wizardExtensionHint(kind string) string {
	switch kind {
	case "video":
		return "video files (.mkv/.mp4/.avi) plus subtitles/nfo"
	case "music":
		return "audio files (.mp3/.flac/.m4a/.ogg/.opus)"
	case "audiobook":
		return "audiobook files (.mp3/.m4b/.flac)"
	case "book":
		return "ebook files (.epub/.pdf/.mobi/.azw3)"
	default:
		return "files"
	}
}

// wizardQualityDefaults returns media-kind-appropriate starting values for a
// per-group quality profile, so e.g. Movies doesn't end up reusing a Music
// profile's audio-format settings and vice versa. Values mirror the examples
// in config.example.toml where applicable.
func wizardQualityDefaults(kind string) config.QualityConfig {
	switch kind {
	case "video":
		return config.QualityConfig{
			WantedResolution:            []string{"480p", "720p", "1080p"},
			WantedQuality:               []string{"sdtv", "hdtv", "webdl", "webrip", "dvdrip", "bluray"},
			CutoffResolution:            "1080p",
			CutoffQuality:               "bluray",
			UseForPriorityResolution:    true,
			UseForPriorityQuality:       true,
			UseForPriorityMinDifference: 10,
		}
	case "music":
		return config.QualityConfig{
			WantedAudioFormats:         []string{"flac", "mp3", "aac", "ogg", "alac", "wma"},
			PreferLossless:             true,
			UseForPriorityAudioFormat:  true,
			UseForPriorityAudioBitrate: true,
		}
	case "audiobook":
		return config.QualityConfig{
			WantedAudioFormats:         []string{"m4b", "mp3", "flac", "aac"},
			UseForPriorityAudioFormat:  true,
			UseForPriorityAudioBitrate: true,
		}
	default: // "book" and anything else: accept everything, no special priority
		return config.QualityConfig{}
	}
}

// wizardRegexDefaults returns a light, generic junk filter for a per-group
// regex - just enough to skip obvious non-releases. Deliberately does not
// attempt language filtering or other highly personal preferences; those are
// easy to add later under Settings -> Regex once the group is working.
func wizardRegexDefaults(kind string) config.RegexConfig {
	switch kind {
	case "video":
		return config.RegexConfig{
			Rejected: []string{`(?i)(\b|_)(sample|trailer|extras?)(\b|_)`},
		}
	default:
		return config.RegexConfig{
			Rejected: []string{`(?i)(\b|_)(sample|trailer)(\b|_)`},
		}
	}
}

// wizardNamingDefault returns a starting file/folder naming template for a
// media group, keyed by wizardMediaGroupDef.key (movies and series need
// different templates despite sharing qualityKind "video"). Field names
// mirror structure.parsertype, the actual struct the template executes
// against (see structure/structure.go), so these render correctly out of the
// box instead of erroring on an unknown field.
func wizardNamingDefault(key string) string {
	switch key {
	case "movies":
		return `{{.Dbmovie.Title}} ({{.Dbmovie.Year}})/{{.Dbmovie.Title}} ({{.Dbmovie.Year}}) [{{.Source.Resolution}} {{.Source.Quality}} {{.Source.Codec}} {{.Source.Audio}}{{if eq .Source.Proper true}} proper{{end}}{{if eq .Source.Extended true}} extended{{end}}] ({{.Source.Imdb}})`
	case "series":
		return `{{.Dbserie.Seriename}}/Season {{.DbserieEpisode.Season}}/{{.Dbserie.Seriename}} - S{{printf "%02s" .DbserieEpisode.Season}}{{range .Episodes}}E{{printf "%02d" . }}{{end}} - {{.DbserieEpisode.Title}} [{{.Source.Resolution}} {{.Source.Quality}} {{.Source.Codec}} {{.Source.Audio}}{{if eq .Source.Proper true}} proper{{end}}] ({{.Source.Tvdb}})`
	case "music":
		return `{{.AlbumArtist.Name}}/{{.Dbalbum.Title}} ({{.Dbalbum.Year}})/{{printf "%02d" .Track}} - {{.Title}}`
	case "audiobooks":
		return `{{.Author.Name}}/{{.Dbaudiobook.Title}}/{{printf "%02d" .Track}} - {{.Title}}`
	case "books":
		return `{{.Author.Name}}/{{.Dbbook.Title}} ({{.Dbbook.Year}})/{{.Dbbook.Title}}`
	default:
		return ""
	}
}

func wizardUpsertMediaGroup(list *[]config.MediaTypeConfig, mtc config.MediaTypeConfig) {
	for i := range *list {
		if (*list)[i].Name == mtc.Name {
			(*list)[i] = mtc
			return
		}
	}

	*list = append(*list, mtc)
}

// wizardEnsureDefaultScheduler creates a single shared "Wizard-Default"
// scheduler the first time it's needed (only if missing, so re-running the
// wizard never resets timing the user tweaked by hand). Unlike quality/regex,
// scheduling cadence doesn't need to differ per media type.
func wizardEnsureDefaultScheduler() {
	names := wizardNames(
		config.GetSettingsSchedulerAll(),
		func(s config.SchedulerConfig) string { return s.Name },
	)
	if wizardNameExists(names, wizardDefaultName) {
		return
	}

	_ = config.UpdateCfgEntry(config.Conf{
		Name: "scheduler_" + wizardDefaultName,
		Data: config.SchedulerConfig{
			Name:                       wizardDefaultName,
			IntervalImdb:               "3d",
			IntervalFeeds:              "1d",
			IntervalFeedsRefreshSeries: "1d",
			IntervalFeedsRefreshMovies: "1d",
			IntervalIndexerMissing:     "40m",
			IntervalIndexerUpgrade:     "60m",
			IntervalIndexerRss:         "15m",
			IntervalScanData:           "1h",
			IntervalScanDataMissing:    "1d",
			IntervalScanDataimport:     "60m",
		},
	})
}

// ---- Step 1: Media groups (selection only - no config.toml writes yet) ----

func renderWizardStepGroups(csrfToken string, state wizardState) gomponents.Node {
	rows := make([]gomponents.Node, 0, len(wizardMediaGroupDefs))

	for _, d := range wizardMediaGroupDefs {
		g := state.Groups[d.key]

		nameDefault := d.defaultName
		if g.Name != "" {
			nameDefault = g.Name
		}

		rows = append(rows, html.Div(
			html.Class("col-md-6 col-lg-4 mb-3"),
			renderFormGroup(
				"wizard_group",
				map[string]string{d.enabledField: "Create a " + d.label + " media group"},
				map[string]string{d.enabledField: "Enable " + d.label},
				d.enabledField, "checkbox", g.Enabled, nil,
			),
			renderFormGroup(
				"wizard_group",
				map[string]string{d.nameField: "Group name"},
				map[string]string{d.nameField: d.label + " Group Name"},
				d.nameField, "text", nameDefault, nil,
			),
		))
	}

	return html.Div(
		html.Class("config-section-enhanced"),
		renderEnhancedPageHeader(
			"fa-solid fa-layer-group",
			"Step 1: Media Groups",
			"Pick which media types this instance should manage. This decides what the next steps ask for - e.g. how many storage paths to create and which file extensions they should accept.",
		),
		html.Form(
			html.Class("config-form"),
			html.ID("wizardStepForm"),
			html.Div(html.Class("row"), gomponents.Group(rows)),
			html.Div(
				html.Class("form-group submit-group mt-3"),
				wizardSaveButton(1, csrfToken),
				wizardNextButton(1, "Skip"),
			),
		),
	)
}

func wizardSaveGroupsStep(
	c *gin.Context,
	state wizardState,
) (alert string, groups map[string]wizardGroupState) {
	groups = make(map[string]wizardGroupState, len(wizardMediaGroupDefs))

	var enabledNames []string

	for _, d := range wizardMediaGroupDefs {
		prev := state.Groups[d.key]

		g := wizardGroupState{
			Enabled:     c.PostForm("wizard_group_"+d.enabledField) != "",
			Name:        strings.TrimSpace(c.PostForm("wizard_group_" + d.nameField)),
			LibraryPath: prev.LibraryPath,
			ImportPath:  prev.ImportPath,
		}
		if g.Name == "" {
			g.Name = d.defaultName
		}

		if g.Enabled {
			enabledNames = append(enabledNames, g.Name)
		}

		groups[d.key] = g
	}

	if len(enabledNames) == 0 {
		return "", groups
	}

	return renderAlert("Selected: "+strings.Join(enabledNames, ", "), "success"), groups
}

// ---- Step 2: Storage paths (templated per group selected in step 1) ----

func renderWizardStepPaths(csrfToken string, state wizardState) gomponents.Node {
	enabled := wizardEnabledGroups(state)
	if len(enabled) == 0 {
		return html.Div(
			html.Class("config-section-enhanced"),
			renderEnhancedPageHeader(
				"fa-solid fa-folder-tree",
				"Step 2: Storage Paths",
				"No media groups were selected in step 1, so there's nothing to create paths for here. Go back to step 1 to pick some, or continue and add paths later under Settings -> Paths.",
			),
			html.Div(html.Class("mt-3"), wizardNextButton(2, "Continue ->")),
		)
	}

	rows := make([]gomponents.Node, 0, len(enabled))

	for _, d := range enabled {
		g := state.Groups[d.key]

		rows = append(rows, html.Div(
			html.Class("col-md-6 mb-4 p-2 border rounded"),
			html.H5(gomponents.Text(g.Name)),
			html.P(
				html.Class("text-muted small"),
				gomponents.Text("Extensions applied automatically: "+wizardExtensionHint(d.qualityKind)),
			),
			renderFormGroup(
				"wizard_path",
				map[string]string{
					"Library" + d.label: "Main storage folder for finished " + g.Name,
				},
				map[string]string{"Library" + d.label: "Library Path"},
				"Library"+d.label, "text", "", nil,
			),
			renderPathCheckControl(csrfToken, "wizard_path_Library"+d.label),
			renderFormGroup(
				"wizard_path",
				map[string]string{
					"Import" + d.label: "Optional: existing folder to scan/import - leave empty to skip",
				},
				map[string]string{"Import" + d.label: "Import Path (optional)"},
				"Import"+d.label, "text", "", nil,
			),
			renderPathCheckControl(csrfToken, "wizard_path_Import"+d.label),
		))
	}

	return html.Div(
		html.Class("config-section-enhanced"),
		renderEnhancedPageHeader(
			"fa-solid fa-folder-tree",
			"Step 2: Storage Paths",
			"One section per media group you enabled - file extensions are set automatically based on that group's type. A Library path is what new downloads land in; an Import path (optional) is for scanning in files you already have.",
		),
		html.Form(
			html.Class("config-form"),
			html.ID("wizardStepForm"),
			html.Div(html.Class("row"), gomponents.Group(rows)),
			html.Div(
				html.Class("form-group submit-group mt-3"),
				wizardSaveButton(2, csrfToken),
				wizardNextButton(2, "Skip"),
			),
		),
	)
}

func wizardSavePathsStep(
	c *gin.Context,
	state wizardState,
) (alert string, groups map[string]wizardGroupState) {
	groups = state.Groups
	if groups == nil {
		groups = map[string]wizardGroupState{}
	}

	var created []string

	for _, d := range wizardEnabledGroups(state) {
		g := groups[d.key]

		if lib := strings.TrimSpace(c.PostForm("wizard_path_Library" + d.label)); lib != "" {
			cfg := config.PathsConfig{Name: g.Name + "-Library", Path: lib}
			wizardApplyExtensions(&cfg, d.qualityKind)

			if err := config.UpdateCfgEntry(config.Conf{Name: "path_" + cfg.Name, Data: cfg}); err == nil {
				g.LibraryPath = cfg.Name
				created = append(created, cfg.Name)
			}
		}

		if imp := strings.TrimSpace(c.PostForm("wizard_path_Import" + d.label)); imp != "" {
			cfg := config.PathsConfig{Name: g.Name + "-Import", Path: imp}
			wizardApplyExtensions(&cfg, d.qualityKind)

			if err := config.UpdateCfgEntry(config.Conf{Name: "path_" + cfg.Name, Data: cfg}); err == nil {
				g.ImportPath = cfg.Name
				created = append(created, cfg.Name)
			}
		}

		groups[d.key] = g
	}

	if len(created) == 0 {
		return "", groups
	}

	return renderAlert("Path(s) saved: "+strings.Join(created, ", "), "success"), groups
}

// ---- Step 3: Indexer ----

func renderWizardStepIndexer(csrfToken string) gomponents.Node {
	return html.Div(
		html.Class("config-section-enhanced"),
		renderEnhancedPageHeader(
			"fa-solid fa-server",
			"Step 3: Indexer",
			"Add a Newznab or Torznab indexer to search for releases.",
		),
		html.Form(
			html.Class("config-form"),
			html.ID("wizardStepForm"),
			renderTemplateSelect("Indexer Template", indexerTemplates),
			html.Div(
				html.Class("row"),
				html.Div(
					html.Class("col-md-6"),
					renderFormGroup(
						"wizard_indexer",
						map[string]string{"Name": "A short label for this indexer"},
						map[string]string{"Name": "Indexer Name"},
						"Name", "text", "MyIndexer", nil,
					),
					renderFormGroup(
						"wizard_indexer",
						map[string]string{"IndexerType": "Newznab (Usenet) or Torznab (torrent)"},
						map[string]string{"IndexerType": "Indexer Type"},
						"IndexerType", "select", "newznab",
						map[string][]string{"options": {"newznab", "torznab"}},
					),
				),
				html.Div(
					html.Class("col-md-6"),
					renderFormGroup(
						"wizard_indexer",
						map[string]string{"URL": "Base URL, without /api"},
						map[string]string{"URL": "URL"},
						"URL", "text", "", nil,
					),
					renderFormGroup(
						"wizard_indexer",
						map[string]string{"Apikey": "API key from your indexer account"},
						map[string]string{"Apikey": "API Key"},
						"Apikey", "text", "", nil,
					),
				),
			),
			html.Div(
				html.Class("form-group submit-group mt-3"),
				wizardTestButton("/api/admin/wizard/test/indexer", csrfToken),
				wizardSaveButton(3, csrfToken),
				wizardNextButton(3, "Skip"),
			),
			html.Div(html.ID("wizardTestResult"), html.Class("mt-2")),
		),
	)
}

func wizardSaveIndexerStep(c *gin.Context) (alert, name string) {
	nm := strings.TrimSpace(c.PostForm("wizard_indexer_Name"))
	rawURL := strings.TrimSpace(c.PostForm("wizard_indexer_URL"))
	apikey := strings.TrimSpace(c.PostForm("wizard_indexer_Apikey"))
	indexerType := c.PostForm("wizard_indexer_IndexerType")

	if rawURL == "" {
		return "", ""
	}

	if nm == "" {
		nm = "MyIndexer"
	}

	if indexerType == "" {
		indexerType = "newznab"
	}

	cfg := config.IndexersConfig{
		Name:           nm,
		IndexerType:    indexerType,
		URL:            rawURL,
		Apikey:         apikey,
		Enabled:        true,
		Limitercalls:   5,
		Limiterseconds: 20,
		MaxEntries:     100,
		RssEntriesloop: 2,
	}

	if err := config.UpdateCfgEntry(config.Conf{Name: "indexer_" + nm, Data: cfg}); err != nil {
		return renderAlert("Failed to save indexer: "+err.Error(), "danger"), ""
	}

	return renderAlert("Indexer '"+nm+"' saved.", "success"), nm
}

// HandleWizardTestIndexer performs a live capability check against the
// entered indexer URL/API key without persisting anything.
func HandleWizardTestIndexer(c *gin.Context) {
	if err := c.Request.ParseForm(); err != nil {
		c.Header("Content-Type", "text/html")
		c.String(http.StatusOK, renderAlert("Failed to parse form: "+err.Error(), "danger"))

		return
	}

	rawURL := strings.TrimSpace(c.PostForm("wizard_indexer_URL"))
	apikey := strings.TrimSpace(c.PostForm("wizard_indexer_Apikey"))

	c.Header("Content-Type", "text/html")

	if rawURL == "" {
		c.String(http.StatusOK, renderAlert("Enter a URL first.", "warning"))
		return
	}

	provider := newznab.NewProvider(newznab.ProviderConfig{
		IndexerName: "wizard-test",
		BaseURL:     rawURL,
		APIKey:      apikey,
		Enabled:     true,
	})

	ctx, cancel := context.WithTimeout(c.Request.Context(), wizardTestTimeout)
	defer cancel()

	if err := provider.TestConnection(ctx); err != nil {
		c.String(http.StatusOK, renderAlert("Connection failed: "+err.Error(), "danger"))
		return
	}

	c.String(http.StatusOK, renderAlert("Connection succeeded.", "success"))
}

// ---- Step 4: Download client ----

func renderWizardStepDownloader(csrfToken string) gomponents.Node {
	return html.Div(
		html.Class("config-section-enhanced"),
		renderEnhancedPageHeader(
			"fa-solid fa-download",
			"Step 4: Download Client",
			"Where should indexer results be sent? Choose 'drone' to just save files to disk without a download client.",
		),
		html.Form(
			html.Class("config-form"),
			html.ID("wizardStepForm"),
			renderTemplateSelect("Download Client Template", downloaderTemplates),
			html.Div(
				html.Class("row"),
				html.Div(
					html.Class("col-md-6"),
					renderFormGroup(
						"wizard_downloader",
						map[string]string{"Name": "A short label for this downloader"},
						map[string]string{"Name": "Downloader Name"},
						"Name", "text", "MyDownloader", nil,
					),
					renderFormGroup(
						"wizard_downloader",
						map[string]string{"DlType": "Which download client to use - leave unset to skip this step"},
						map[string]string{"DlType": "Client Type"},
						"DlType", "select", "",
						map[string][]string{
							"options": {
								"", "drone", "nzbget", "sabnzbd", "qbittorrent",
								"deluge", "rtorrent", "transmission",
							},
						},
					),
					renderFormGroup(
						"wizard_downloader",
						map[string]string{"Hostname": "Host or IP of the download client (leave empty for drone)"},
						map[string]string{"Hostname": "Hostname"},
						"Hostname", "text", "", nil,
					),
					renderFormGroup(
						"wizard_downloader",
						map[string]string{"Port": "Port of the download client's Web UI/API"},
						map[string]string{"Port": "Port"},
						"Port", "number", 0, nil,
					),
				),
				html.Div(
					html.Class("col-md-6"),
					renderFormGroup(
						"wizard_downloader",
						map[string]string{"Username": "Leave empty if not required"},
						map[string]string{"Username": "Username"},
						"Username", "text", "", nil,
					),
					renderFormGroup(
						"wizard_downloader",
						map[string]string{"Password": "For SABnzbd, put your API key here instead"},
						map[string]string{"Password": "Password / API Key"},
						"Password", "text", "", nil,
					),
				),
			),
			html.Div(
				html.Class("form-group submit-group mt-3"),
				wizardTestButton("/api/admin/wizard/test/downloader", csrfToken),
				wizardSaveButton(4, csrfToken),
				wizardNextButton(4, "Skip"),
			),
			html.Div(html.ID("wizardTestResult"), html.Class("mt-2")),
		),
	)
}

func wizardSaveDownloaderStep(c *gin.Context) (alert, name string) {
	nm := strings.TrimSpace(c.PostForm("wizard_downloader_Name"))
	dlType := c.PostForm("wizard_downloader_DlType")
	hostname := strings.TrimSpace(c.PostForm("wizard_downloader_Hostname"))
	port, _ := strconv.Atoi(c.PostForm("wizard_downloader_Port"))
	username := c.PostForm("wizard_downloader_Username")
	password := c.PostForm("wizard_downloader_Password")

	if dlType == "" {
		return "", ""
	}

	if nm == "" {
		nm = "MyDownloader"
	}

	cfg := config.DownloaderConfig{
		Name:     nm,
		DlType:   dlType,
		Hostname: hostname,
		Port:     port,
		Username: username,
		Password: password,
		Enabled:  true,
	}

	if err := config.UpdateCfgEntry(config.Conf{Name: "downloader_" + nm, Data: cfg}); err != nil {
		return renderAlert("Failed to save download client: "+err.Error(), "danger"), ""
	}

	return renderAlert("Download client '"+nm+"' saved.", "success"), nm
}

// HandleWizardTestDownloader builds a throwaway provider instance from the
// entered fields (never registered/persisted) and calls its TestConnection.
func HandleWizardTestDownloader(c *gin.Context) {
	if err := c.Request.ParseForm(); err != nil {
		c.Header("Content-Type", "text/html")
		c.String(http.StatusOK, renderAlert("Failed to parse form: "+err.Error(), "danger"))

		return
	}

	dlType := c.PostForm("wizard_downloader_DlType")
	hostname := strings.TrimSpace(c.PostForm("wizard_downloader_Hostname"))
	port, _ := strconv.Atoi(c.PostForm("wizard_downloader_Port"))
	username := c.PostForm("wizard_downloader_Username")
	password := c.PostForm("wizard_downloader_Password")

	c.Header("Content-Type", "text/html")

	if dlType == "" || dlType == "drone" {
		c.String(http.StatusOK, renderAlert("This client type has nothing to test.", "warning"))
		return
	}

	if hostname == "" {
		c.String(http.StatusOK, renderAlert("Enter a hostname first.", "warning"))
		return
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), wizardTestTimeout)
	defer cancel()

	if err := wizardTestDownloaderConnection(ctx, dlType, hostname, port, username, password); err != nil {
		c.String(http.StatusOK, renderAlert("Connection failed: "+err.Error(), "danger"))
		return
	}

	c.String(http.StatusOK, renderAlert("Connection succeeded.", "success"))
}

func wizardTestDownloaderConnection(
	ctx context.Context,
	dlType, hostname string,
	port int,
	username, password string,
) error {
	switch dlType {
	case "qbittorrent":
		p, err := qbittorrent.NewProvider(hostname, port, username, password, false)
		if err != nil {
			return err
		}

		return p.TestConnection(ctx)
	case "sabnzbd":
		// SABnzbd authenticates via API key only - the wizard reuses the Password field for it.
		p, err := sabnzbd.NewProvider(hostname, port, password, false)
		if err != nil {
			return err
		}

		return p.TestConnection(ctx)
	case "nzbget":
		p, err := nzbget.NewProvider(hostname, port, username, password, false)
		if err != nil {
			return err
		}

		return p.TestConnection(ctx)
	case "deluge":
		p := deluge.NewProvider(fmt.Sprintf("http://%s:%d", hostname, port), username, password)
		return p.TestConnection(ctx)
	case "transmission":
		p := transmission.NewProvider(fmt.Sprintf("http://%s:%d", hostname, port), username, password)
		return p.TestConnection(ctx)
	case "rtorrent":
		p, err := rtorrent.NewProvider(hostname, port, username, password, false, "")
		if err != nil {
			return err
		}

		return p.TestConnection(ctx)
	default:
		return fmt.Errorf("unknown download client type: %s", dlType)
	}
}

// ---- Step 5: Lists ----
//
// Embeds the real Lists Settings section (renderListsConfig), which already
// covers every ListType the app supports and unlimited "Add List", instead of
// a restricted single-item wizard form.

func renderWizardStepLists(csrfToken string) gomponents.Node {
	return html.Div(
		html.Class("config-section-enhanced"),
		renderEnhancedPageHeader(
			"fa-solid fa-list-check",
			"Step 5: Lists",
			"Add one or more lists - every list type is available here (Trakt, TMDB, Plex/Jellyfin watchlists, scrapers, IRC, and the manual *config file types). Save, then Continue - you'll attach these to media groups in step 6.",
		),
		renderListsConfig(config.GetSettingsListAll(), csrfToken),
		html.Div(html.Class("mt-3"), wizardNextButton(5, "Continue ->")),
	)
}

// ---- Step 6: Finalize (attach lists, create per-group quality/regex, save) ----

func renderWizardStepFinalize(csrfToken string, state wizardState) gomponents.Node {
	enabled := wizardEnabledGroups(state)
	if len(enabled) == 0 {
		return html.Div(
			html.Class("config-section-enhanced"),
			renderEnhancedPageHeader(
				"fa-solid fa-check-double",
				"Step 6: Finalize Groups",
				"No media groups were selected in step 1, so there's nothing to finalize.",
			),
			html.Div(html.Class("mt-3"), wizardNextButton(6, "Finish")),
		)
	}

	warn := ""
	if state.Indexer == "" || state.Downloader == "" {
		warn = " Note: no indexer/download client was configured in this run, so each group's quality profile will be created with an empty indexer/downloader - add one under Settings -> Quality (or go back to steps 3/4) before expecting searches to actually run."
	}

	listNames := wizardNames(config.GetSettingsListAll(), func(l config.ListsConfig) string { return l.Name })

	rows := make([]gomponents.Node, 0, len(enabled))

	for _, d := range enabled {
		g := state.Groups[d.key]

		pathSummary := "no library path configured"
		if g.LibraryPath != "" {
			pathSummary = "Library: " + g.LibraryPath
			if g.ImportPath != "" {
				pathSummary += ", Import: " + g.ImportPath
			}
		}

		rows = append(rows, html.Div(
			html.Class("col-md-6 mb-4 p-2 border rounded"),
			html.H5(gomponents.Text(g.Name)),
			html.P(html.Class("text-muted small"), gomponents.Text(pathSummary)),
			renderFormGroup(
				"wizard_finalize",
				map[string]string{"Lists" + d.label: "Feed(s) that add wanted " + g.Name},
				map[string]string{"Lists" + d.label: "Lists"},
				"Lists"+d.label, "selectarray", []string{},
				map[string][]string{"options": listNames},
			),
		))
	}

	return html.Div(
		html.Class("config-section-enhanced"),
		renderEnhancedPageHeader(
			"fa-solid fa-check-double",
			"Step 6: Finalize Groups",
			"Attach lists to each group, then Finish. A dedicated quality profile and regex filter are created per group, tailored to that media kind."+warn,
		),
		html.Form(
			html.Class("config-form"),
			html.ID("wizardStepForm"),
			html.Div(html.Class("row"), gomponents.Group(rows)),
			html.Div(
				html.Class("form-group submit-group mt-3"),
				wizardSaveButton(6, csrfToken),
				wizardNextButton(6, "Skip & Finish"),
			),
		),
	)
}

func wizardSaveFinalizeStep(c *gin.Context, state wizardState) string {
	live := config.GetSettingsMediaAll()
	if live == nil {
		return renderAlert("Configuration not loaded.", "danger")
	}

	// Deep-copy the slices - GetSettingsMediaAll returns a pointer straight into
	// the live snapshot, so mutating it in place would race with readers.
	mc := config.MediaConfig{
		Movies:     append([]config.MediaTypeConfig(nil), live.Movies...),
		Series:     append([]config.MediaTypeConfig(nil), live.Series...),
		Books:      append([]config.MediaTypeConfig(nil), live.Books...),
		AudioBooks: append([]config.MediaTypeConfig(nil), live.AudioBooks...),
		Music:      append([]config.MediaTypeConfig(nil), live.Music...),
	}

	// A quality/regex/scheduler profile is created for every enabled group
	// regardless of whether an indexer/downloader were configured in steps 3/4
	// - otherwise TemplateQuality/TemplateScheduler are left blank and the
	// group is unusable even after the user adds an indexer later. Only the
	// actual indexer/downloader wiring inside the quality's Indexer entry
	// depends on state.Indexer/state.Downloader (left blank if missing, ready
	// to fill in under Settings -> Quality).
	wizardEnsureDefaultScheduler()

	scheduler := wizardDefaultName

	var created []string

	for _, d := range wizardEnabledGroups(state) {
		g := state.Groups[d.key]

		mtc := config.MediaTypeConfig{
			Name:              g.Name,
			Naming:            wizardNamingDefault(d.key),
			TemplateScheduler: scheduler,
			AudibleRegion:     d.audibleRegion,
		}

		if g.LibraryPath != "" {
			mtc.Data = []config.MediaDataConfig{{TemplatePath: g.LibraryPath}}
		}

		if g.ImportPath != "" {
			mtc.DataImport = []config.MediaDataImportConfig{{TemplatePath: g.ImportPath}}
		}

		qualityName := g.Name + "-Quality"
		regexName := g.Name + "-Regex"

		regexCfg := wizardRegexDefaults(d.qualityKind)
		regexCfg.Name = regexName
		_ = config.UpdateCfgEntry(config.Conf{Name: "regex_" + regexName, Data: regexCfg})

		quality := wizardQualityDefaults(d.qualityKind)
		quality.Name = qualityName
		quality.Indexer = []config.QualityIndexerConfig{{
			TemplateIndexer:    state.Indexer,    // may be "" if step 3 was skipped
			TemplateDownloader: state.Downloader, // may be "" if step 4 was skipped
			TemplateRegex:      regexName,
			TemplatePathNzb:    g.LibraryPath,
		}}

		_ = config.UpdateCfgEntry(config.Conf{Name: "quality_" + qualityName, Data: quality})

		mtc.TemplateQuality = qualityName

		lists := wizardNonEmpty(c.PostFormArray("wizard_finalize_Lists" + d.label))
		for _, l := range lists {
			mtc.Lists = append(mtc.Lists, config.MediaListsConfig{
				Name:              g.Name + "-" + l,
				TemplateList:      l,
				TemplateQuality:   qualityName,
				TemplateScheduler: scheduler,
				Enabled:           true,
			})
		}

		wizardUpsertMediaGroup(d.target(&mc), mtc)
		created = append(created, g.Name)
	}

	if len(created) == 0 {
		return ""
	}

	if err := config.UpdateCfgEntryAny(&mc); err != nil {
		return renderAlert("Failed to save media groups: "+err.Error(), "danger")
	}

	wizardEnableScheduler()

	return renderAlert(
		"Media group(s) saved: "+strings.Join(
			created,
			", ",
		)+". Restart the application so the scheduler and workers pick everything up.",
		"success",
	)
}

// wizardEnableScheduler flips General.SchedulerDisabled off if it's still the
// ClearCfg fresh-install default (true) - a user who just finished the wizard
// clearly wants automated searches to actually run. This takes effect
// immediately for future job dispatch (utils/jobs.go reads it live), but the
// scheduler/worker goroutines themselves are only wired up at startup, hence
// the restart advice shown on the Finish step.
func wizardEnableScheduler() {
	general := config.GetSettingsGeneral()
	if general == nil || !general.SchedulerDisabled {
		return
	}

	updated := *general
	updated.SchedulerDisabled = false
	_ = config.UpdateCfgEntryAny(&updated)
}

// ---- Step 7: Finish ----

func renderWizardStepFinish() gomponents.Node {
	paths := config.GetSettingsPathAll()
	lists := config.GetSettingsListAll()
	media := config.GetSettingsMediaAll()

	groupCount := 0
	if media != nil {
		groupCount = len(media.Movies) + len(media.Series) + len(media.Music) +
			len(media.AudioBooks) + len(media.Books)
	}

	body := []gomponents.Node{
		renderEnhancedPageHeader(
			"fa-solid fa-flag-checkered",
			"Setup Complete",
			"Fine-tune anything, or add more paths, indexers, lists, and media groups, from Configuration in the sidebar.",
		),
		html.Div(
			html.Class("alert alert-warning d-flex align-items-center"),
			html.I(html.Class("fa-solid fa-triangle-exclamation me-2")),
			html.Div(gomponents.Text(
				"Restart the application now. Paths/indexers/downloaders/lists/media groups take effect immediately, but the scheduler and worker pools that actually run searches and downloads are only set up at startup.",
			)),
		),
		html.Ul(
			html.Li(gomponents.Text(fmt.Sprintf("%d path(s) configured", len(paths)))),
			html.Li(gomponents.Text(fmt.Sprintf("%d list(s) configured", len(lists)))),
			html.Li(gomponents.Text(fmt.Sprintf("%d media group(s) configured", groupCount))),
		),
	}

	body = append(body, html.Div(
		html.Class("mt-3"),
		html.A(
			html.Class("btn btn-primary me-2"),
			html.Href("/api/admin/config/media"),
			gomponents.Text("Review Media Groups"),
		),
		html.A(
			html.Class("btn btn-outline-secondary"),
			html.Href("/api/admin/wizard/dismiss"),
			gomponents.Text("Go to Dashboard"),
		),
	))

	return html.Div(html.Class("config-section-enhanced"), gomponents.Group(body))
}
