FROM golang:latest
LABEL maintainer "Kellerman81 <Kellerman81@gmail.com>"
RUN mkdir C:\app
RUN mkdir C:\app/config
RUN mkdir C:\app/databases
RUN mkdir C:\app/logs
RUN mkdir C:\app/backup
RUN mkdir C:\app/temp
WORKDIR C:\app
USER 0:0
VOLUME C:\app/databases
VOLUME C:\app/config
VOLUME C:\app/logs
COPY ./config/ /app/config/
COPY ./databases/ /app/databases/
COPY ./docs/ /app/docs/
COPY ./schema/ /app/schema/
COPY ./LICENSE /app/LICENSE
COPY ./README.md /app/README.md
COPY ./go_media_downloader* /app/
COPY ./init_imdb* /app/

# Expose port 9090 to the outside world
EXPOSE 9090
CMD ["/app/go_media_downloader.exe"]