// This file is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/Kellerman81/go_media_downloader/goadmin/models"

	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// example end
//
var Generators = map[string]table.Generator{
	"dbmovies":                models.GetDbmoviesTable,
	"dbmovie_titles":          models.GetDbmovieTitlesTable,
	"dbserie_alternates":      models.GetDbserieAlternatesTable,
	"dbserie_episodes":        models.GetDbserieEpisodesTable,
	"dbseries":                models.GetDbseriesTable,
	"movie_files":             models.GetMovieFilesTable,
	"movie_histories":         models.GetMovieHistoriesTable,
	"movies":                  models.GetMoviesTable,
	"qualities":               models.GetQualitiesTable,
	"serie_episode_files":     models.GetSerieEpisodeFilesTable,
	"serie_episode_histories": models.GetSerieEpisodeHistoriesTable,
	"serie_episodes":          models.GetSerieEpisodesTable,
	"series":                  models.GetSeriesTable,
	"movie_file_unmatcheds":   models.GetMovieFileUnmatchedsTable,
	"job_histories":           models.GetJobHistoriesTable,
	"indexer_fails":           models.GetIndexerFailsTable,
	"serie_file_unmatcheds":   models.GetSerieFileUnmatchedsTable,
	"r_sshistories":           models.GetRSshistoriesTable,
	"stats":                   models.GetStatsTable,
	"scheduler":               models.GetSchedulerTable,
	"queue":                   models.GetQueueTable,
	// generators end
}
