[global] # global not yet used so use series config below
identifiedby = "ep" #or date
upgrade = "yes"
search = "yes"
[[series]]
name = "Battlestar Galactica 2003" #primary name for series
alternatename = ["Battlestar Galactica (2003)"] #Alternate Names for series - will also be imported by tvdb api
tvdb_id = 73545 # currently required - except if source is none
source = "tvdb" #chose 'none' if you want to manange the episodes manually - possible values: tvdb, none
target = "/series/BG2k3" #Path where to put your series - optional
identifiedby = "ep" #or date ep is default! (only for initial import - then you change it in the database)
dont_upgrade = "yes" # (only for initial import - then you change it in the database)
dont_search = "yes" # (only for initial import - then you change it in the database)
search_specials = "yes" #should we search for Season 0 - Specials? (only for initial import - then you change it in the database)
ignore_runtime = "no" #By Default the runtime of episodes will be checked on import - here you can disable this (only for initial import - then you change it in the database)