package acoustid

import (
	"context"
	"errors"
	"time"

	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2"
	"github.com/Kellerman81/go_media_downloader/pkg/main/apiexternal_v2/base"
	"github.com/Kellerman81/go_media_downloader/pkg/main/logger"
)

//
// AcoustID Provider - Audio fingerprint lookup service
// API: https://acoustid.org/webservice
// Used to identify music by audio fingerprint (generated by chromaprint/fpcalc)
//

const (
	defaultBaseURL = "https://api.acoustid.org/v2"
)

// Provider implements the audio fingerprint lookup provider for AcoustID.
type Provider struct {
	*base.BaseClient
	apiKey string
}

// NewProviderWithConfig creates a new AcoustID provider with custom config.
func NewProviderWithConfig(config base.ClientConfig, apiKey string) *Provider {
	config.Name = "acoustid"
	if config.BaseURL == "" {
		config.BaseURL = defaultBaseURL
	}

	if config.Timeout == 0 {
		config.Timeout = 30 * time.Second
	}

	// AcoustID rate limit: 3 requests per second
	if config.RateLimitCalls == 0 {
		config.RateLimitCalls = 3
	}

	if config.RateLimitSeconds == 0 {
		config.RateLimitSeconds = 1
	}

	return &Provider{
		BaseClient: base.NewBaseClient(config),
		apiKey:     apiKey,
	}
}

// NewProvider creates a new AcoustID provider with an API key.
// Get your API key at: https://acoustid.org/api-key
func NewProvider(apiKey string) *Provider {
	return NewProviderWithConfig(base.ClientConfig{}, apiKey)
}

// GetProviderType returns the provider type.
func (p *Provider) GetProviderType() apiexternal_v2.ProviderType {
	return apiexternal_v2.ProviderAcoustID
}

// GetProviderName returns the provider name.
func (p *Provider) GetProviderName() string {
	return "acoustid"
}

//
// Lookup Methods
//

// LookupByFingerprint looks up a recording by its audio fingerprint.
// The fingerprint should be generated using chromaprint/fpcalc.
// Duration is the track duration in seconds.
func (p *Provider) LookupByFingerprint(
	ctx context.Context,
	fingerprint string,
	duration int,
) ([]apiexternal_v2.RecordingMatch, error) {
	buf := logger.PlAddBuffer.Get()
	buf.WriteString("/lookup?client=")
	buf.WriteURL(p.apiKey)
	buf.WriteString("&fingerprint=")
	buf.WriteURL(fingerprint)
	buf.WriteString("&duration=")
	buf.WriteInt(duration)
	buf.WriteString("&meta=recordings%2Breleasegroups%2Breleases%2Btracks%2Bcompress&format=json")

	endpoint := buf.String()
	logger.PlAddBuffer.Put(buf)

	var response acoustidLookupResponse
	if err := p.MakeRequest(ctx, "GET", endpoint, nil, &response, nil); err != nil {
		return nil, err
	}

	if response.Status != "ok" {
		return nil, errors.New(logger.JoinStrings("acoustid error: ", response.Status))
	}

	return convertLookupResults(response.Results), nil
}

// LookupByFingerprintWithMeta looks up a recording with specific metadata fields.
// Available meta options: recordings, recordingids, releases, releaseids,
// releasegroups, releasegroupids, tracks, compress, usermeta, sources.
func (p *Provider) LookupByFingerprintWithMeta(
	ctx context.Context,
	fingerprint string,
	duration int,
	meta string,
) ([]apiexternal_v2.RecordingMatch, error) {
	buf := logger.PlAddBuffer.Get()
	buf.WriteString("/lookup?client=")
	buf.WriteURL(p.apiKey)
	buf.WriteString("&fingerprint=")
	buf.WriteURL(fingerprint)
	buf.WriteString("&duration=")
	buf.WriteInt(duration)
	buf.WriteString("&meta=")
	buf.WriteURL(meta)
	buf.WriteString("&format=json")

	endpoint := buf.String()
	logger.PlAddBuffer.Put(buf)

	var response acoustidLookupResponse
	if err := p.MakeRequest(ctx, "GET", endpoint, nil, &response, nil); err != nil {
		return nil, err
	}

	if response.Status != "ok" {
		return nil, errors.New(logger.JoinStrings("acoustid error: ", response.Status))
	}

	return convertLookupResults(response.Results), nil
}

// LookupByTrackID looks up recordings by AcoustID track ID.
func (p *Provider) LookupByTrackID(
	ctx context.Context,
	trackID string,
) ([]apiexternal_v2.RecordingMatch, error) {
	buf := logger.PlAddBuffer.Get()
	buf.WriteString("/lookup?client=")
	buf.WriteURL(p.apiKey)
	buf.WriteString("&trackid=")
	buf.WriteURL(trackID)
	buf.WriteString("&meta=")
	buf.WriteURL("recordings+releasegroups+releases+tracks+compress")
	buf.WriteString("&format=json")

	endpoint := buf.String()
	logger.PlAddBuffer.Put(buf)

	var response acoustidLookupResponse
	if err := p.MakeRequest(ctx, "GET", endpoint, nil, &response, nil); err != nil {
		return nil, err
	}

	if response.Status != "ok" {
		return nil, errors.New(logger.JoinStrings("acoustid error: ", response.Status))
	}

	return convertLookupResults(response.Results), nil
}

// BatchLookup performs multiple fingerprint lookups in a single request.
// Each item in the batch should have fingerprint and duration.
func (p *Provider) BatchLookup(
	ctx context.Context,
	items []FingerprintItem,
) ([][]apiexternal_v2.RecordingMatch, error) {
	if len(items) == 0 {
		return nil, nil
	}

	// AcoustID supports up to 3 fingerprints per request
	const maxBatchSize = 3
	if len(items) > maxBatchSize {
		items = items[:maxBatchSize]
	}

	buf := logger.PlAddBuffer.Get()
	buf.WriteString("/lookup?client=")
	buf.WriteURL(p.apiKey)
	buf.WriteString("&meta=recordings%2Breleasegroups%2Breleases%2Btracks%2Bcompress")
	buf.WriteString("&format=json")
	buf.WriteString("&batch=1")

	for i, item := range items {
		buf.WriteString("&fingerprint.")
		buf.WriteInt(i)
		buf.WriteString("=")
		buf.WriteURL(item.Fingerprint)
		buf.WriteString("&duration.")
		buf.WriteInt(i)
		buf.WriteString("=")
		buf.WriteInt(item.Duration)
	}

	endpoint := buf.String()
	logger.PlAddBuffer.Put(buf)

	var response acoustidLookupResponse
	if err := p.MakeRequest(ctx, "GET", endpoint, nil, &response, nil); err != nil {
		return nil, err
	}

	if response.Status != "ok" {
		return nil, errors.New(logger.JoinStrings("acoustid error: ", response.Status))
	}

	// Group results by index
	results := make([][]apiexternal_v2.RecordingMatch, len(items))
	for i := range results {
		results[i] = make([]apiexternal_v2.RecordingMatch, 0)
	}

	for i := range response.Results {
		if response.Results[i].Index < len(results) {
			results[response.Results[i].Index] = append(
				results[response.Results[i].Index],
				convertResult(&response.Results[i])...)
		}
	}

	return results, nil
}

// FingerprintItem represents a fingerprint lookup item for batch operations.
type FingerprintItem struct {
	Fingerprint string
	Duration    int // Duration in seconds
}

//
// Submit Methods (requires application key with submit permission)
//

// SubmitFingerprint submits a new fingerprint to AcoustID.
// This requires an API key with submit permission.
func (p *Provider) SubmitFingerprint(
	ctx context.Context,
	submission FingerprintSubmission,
) error {
	buf := logger.PlAddBuffer.Get()
	buf.WriteString("/submit?client=")
	buf.WriteURL(p.apiKey)
	buf.WriteString("&format=json")

	if submission.UserAPIKey != "" {
		buf.WriteString("&user=")
		buf.WriteURL(submission.UserAPIKey)
	}

	buf.WriteString("&fingerprint=")
	buf.WriteURL(submission.Fingerprint)
	buf.WriteString("&duration=")
	buf.WriteInt(submission.Duration)

	// Optional metadata
	if submission.MBRecordingID != "" {
		buf.WriteString("&mbid=")
		buf.WriteURL(submission.MBRecordingID)
	}

	if submission.Track != "" {
		buf.WriteString("&track=")
		buf.WriteURL(submission.Track)
	}

	if submission.Artist != "" {
		buf.WriteString("&artist=")
		buf.WriteURL(submission.Artist)
	}

	if submission.Album != "" {
		buf.WriteString("&album=")
		buf.WriteURL(submission.Album)
	}

	if submission.AlbumArtist != "" {
		buf.WriteString("&albumartist=")
		buf.WriteURL(submission.AlbumArtist)
	}

	if submission.Year > 0 {
		buf.WriteString("&year=")
		buf.WriteInt(submission.Year)
	}

	if submission.TrackNo > 0 {
		buf.WriteString("&trackno=")
		buf.WriteInt(submission.TrackNo)
	}

	if submission.DiscNo > 0 {
		buf.WriteString("&discno=")
		buf.WriteInt(submission.DiscNo)
	}

	endpoint := buf.String()
	logger.PlAddBuffer.Put(buf)

	var response acoustidSubmitResponse
	if err := p.MakeRequest(ctx, "POST", endpoint, nil, &response, nil); err != nil {
		return err
	}

	if response.Status != "ok" {
		return errors.New(logger.JoinStrings("acoustid submit error: ", response.Status))
	}

	return nil
}

// FingerprintSubmission represents data for submitting a new fingerprint.
type FingerprintSubmission struct {
	Fingerprint   string
	Duration      int    // Duration in seconds
	UserAPIKey    string // User API key for attribution
	MBRecordingID string // MusicBrainz recording ID
	Track         string // Track title
	Artist        string
	Album         string
	AlbumArtist   string
	Year          int
	TrackNo       int
	DiscNo        int
}
