name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare
      run: go get
      
    - name: Build
      run: go build -v ./...
      
    - name: Build Linux64
      run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o go_media_downloader-amd64-linux main.go
      
    - name: Build Linux32
      run: CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -o go_media_downloader-x86-linux main.go
      
    - name: Build Windows64
      run: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o go_media_downloader-amd64-win.exe main.go
      
    - name: Build Windows32
      run: CGO_ENABLED=1 GOOS=windows GOARCH=386 go build -o go_media_downloader-x86-win.exe main.go
      
    - name: Build Macos64
      run: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o go_media_downloader-amd64-macos main.go
      
    - name: Upload Windows32 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-x86-win.exe
        path: go_media_downloader-x86-win.exe
        
    - name: Upload Windows64 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-amd64-win.exe
        path: go_media_downloader-amd64-win.exe
        
    - name: Upload Linux32 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-x86-linux
        path: go_media_downloader-x86-linux
        
    - name: Upload Linux64 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-amd64-linux
        path: go_media_downloader-amd64-linux
        
    - name: Upload Macos binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-amd64-macos
        path: go_media_downloader-amd64-macos

    - name: Zip Win32 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-windows-x86.zip'
        exclusions: '*.git* /.github/* /api/* /apiexternal/* /config/* /database/* /logger/* /newznab/* /nzbget/* /scanner/* /scheduler/* /tasks/* /utils/* /views/* Dockerfile go.* *.zip *.go go_media_downloader-*-linux  go_media_downloader-*-macos  go_media_downloader-amd64-win.exe'

    - name: Zip Win64 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-windows-x64.zip'
        exclusions: '*.git* /.github/* /api/* /apiexternal/* /config/* /database/* /logger/* /newznab/* /nzbget/* /scanner/* /scheduler/* /tasks/* /utils/* /views/* Dockerfile go.* *.zip *.go go_media_downloader-*-linux  go_media_downloader-*-macos  go_media_downloader-x86-win.exe'

    - name: Zip Linux32 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-linux-x86.zip'
        exclusions: '*.git* /.github/* /api/* /apiexternal/* /config/* /database/* /logger/* /newznab/* /nzbget/* /scanner/* /scheduler/* /tasks/* /utils/* /views/* Dockerfile go.* *.zip *.go go_media_downloader-*-win.exe  go_media_downloader-*-macos  go_media_downloader-amd64-linux'

    - name: Zip Linux64 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-linux-x64.zip'
        exclusions: '*.git* /.github/* /api/* /apiexternal/* /config/* /database/* /logger/* /newznab/* /nzbget/* /scanner/* /scheduler/* /tasks/* /utils/* /views/* Dockerfile go.* *.zip *.go go_media_downloader-*-win.exe  go_media_downloader-*-macos  go_media_downloader-x86-linux'
    
    - name: Zip Mac64 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-macos-x64.zip'
        exclusions: '*.git* /.github/* /api/* /apiexternal/* /config/* /database/* /logger/* /newznab/* /nzbget/* /scanner/* /scheduler/* /tasks/* /utils/* /views/* Dockerfile go.* *.zip *.go go_media_downloader-*-win.exe  go_media_downloader-*-linux  go_media_downloader-x86-macos'

    - name: Development Release
      if: ${{ github.event_name == 'push' }}
      uses: marvinpinto/action-automatic-releases@v1.1.2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: latest_develop
        title: "Latest development build"
        files: |
          develop-macos-x64.zip
          develop-linux-x64.zip
          develop-windows-x64.zip
          develop-linux-x86.zip
          develop-windows-x86.zip