name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - id: commit
      uses: pr-mpt/actions-commit-hash@v1
    
    - name: Get current version
      id: version
      run: echo "::set-output name=version::0.1.1"

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@v2.2.0
      with:
          dest: ./pkg/main
          prefix: go_media_downloader
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/amd64
          v: truec:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-sandbox\workbench\workbench.html
          x: false
          race: false
          ldflags: -s -w -X 'main.version=${{ steps.version.outputs.version }}' -X 'main.githash=${{ steps.commit.outputs.short }}' -X 'main.buildstamp=${{ steps.date.outputs.date }}'
          buildmode: default
          working_dir: pkg/main
    
    - name: Build with xgo imdb
      uses: crazy-max/ghaction-xgo@v2.2.0
      with:
          dest: ./pkg/imdb
          prefix: imdb
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w -X 'main.version=${{ steps.version.outputs.version }}' -X 'main.githash=${{ steps.commit.outputs.short }}' -X 'main.buildstamp=${{ steps.date.outputs.date }}'
          buildmode: default
          working_dir: pkg/imdb
    
    - name: Rename Win32 binary
      run: mv ./pkg/imdb/imdb-windows-4.0-386.exe init_imdb.exe

    - name: Rename Win32 binary dl
      run: mv ./pkg/main/go_media_downloader-windows-4.0-386.exe go_media_downloader.exe

    - name: Zip Win32 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-windows-x86.zip'
        exclusions: '*.git* /.github/* /pkg/* Dockerfile go.* *.zip *.go go_media_downloader-*'

    - name: Rename Win64 binary
      run: mv ./pkg/imdb/imdb-windows-4.0-amd64.exe init_imdb.exe

    - name: Rename Win64 binary dl
      run: mv ./pkg/main/go_media_downloader-windows-4.0-amd64.exe go_media_downloader.exe

    - name: Zip Win64 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-windows-x64.zip'
        exclusions: '*.git* /.github/* /pkg/* Dockerfile go.* *.zip *.go go_media_downloader-*'

    - name: Remove Win binary
      run: rm init_imdb.exe

    - name: Remove Win binary dl
      run: rm ./go_media_downloader.exe

    - name: Rename Linux32 binary
      run: mv ./pkg/imdb/imdb-linux-386 init_imdb

    - name: Rename Linux32 binary dl
      run: mv ./pkg/main/go_media_downloader-linux-386 go_media_downloader

    - name: Zip Linux32 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-linux-x86.zip'
        exclusions: '*.git* /.github/* /pkg/* Dockerfile go.* *.zip *.go go_media_downloader-*'

    - name: Rename Linux64 binary
      run: mv ./pkg/imdb/imdb-linux-amd64 init_imdb

    - name: Rename Linux64 binary dl
      run: mv ./pkg/main/go_media_downloader-linux-amd64 go_media_downloader

    - name: Zip Linux64 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-linux-x64.zip'
        exclusions: '*.git* /.github/* /pkg/* Dockerfile go.* *.zip *.go go_media_downloader-*'
    
    - name: Rename Mac64 binary
      run: mv ./pkg/imdb/imdb-darwin-10.16-amd64 init_imdb

    - name: Rename Mac64 binary dl
      run: mv ./pkg/main/go_media_downloader-darwin-10.16-amd64 go_media_downloader

    - name: Zip Mac64 binary
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'develop-macos-x64.zip'
        exclusions: '*.git* /.github/* /pkg/* Dockerfile go.* *.zip *.go go_media_downloader-*'

    - name: Development Release
      if: ${{ github.event_name == 'push' }}
      uses: marvinpinto/action-automatic-releases@v1.1.2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: latest_develop
        title: "Latest development build"
        files: |
          develop-macos-x64.zip
          develop-linux-x64.zip
          develop-windows-x64.zip
          develop-linux-x86.zip
          develop-windows-x86.zip