name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare
      run: go get
      
    - name: Build
      run: go build -v ./...
      
    - name: Build Linux64
      run: GOOS=linux GOARCH=amd64 go build -o go_media_downloader-amd64-linux main.go
      
    - name: Build Linux32
      run: GOOS=linux GOARCH=386 go build -o go_media_downloader-x86-linux main.go
      
    - name: Build Windows64
      run: GOOS=windows GOARCH=amd64 go build -o go_media_downloader-amd64-win.exe main.go
      
    - name: Build Windows32
      run: GOOS=windows GOARCH=386 go build -o go_media_downloader-x86-win.exe main.go
      
    - name: Build Macos64
      run: GOOS=darwin GOARCH=amd64 go build -o go_media_downloader-amd64-macos main.go
      
    - name: Upload Windows32 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-x86-win.exe
        path: dist/go_media_downloader-x86-win.exe
        
    - name: Upload Windows64 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-amd64-win.exe
        path: dist/go_media_downloader-amd64-win.exe
        
    - name: Upload Linux32 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-x86-linux
        path: dist/go_media_downloader-x86-linux
        
    - name: Upload Linux64 binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-amd64-linux
        path: dist/go_media_downloader-amd64-linux
        
    - name: Upload Macos binary
      uses: actions/upload-artifact@v2
      with:
        name: go_media_downloader-amd64-macos
        path: dist/go_media_downloader-amd64-macos
